import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Terms of Service — PolicyForge",
};

export default function TermsPage() {
  return (
    <section className="py-16">
      <div className="max-w-3xl mx-auto px-4 sm:px-6 prose prose-sm">
        <h1>Terms of Service</h1>
        <p><strong>Last updated:</strong> March 25, 2026</p>

        <p>
          These Terms of Service (&quot;Terms&quot;) govern your access to and use of the PolicyForge
          website and services at policyforge.site (&quot;Service&quot;) operated by PolicyForge (&quot;we,&quot;
          &quot;us,&quot; or &quot;our&quot;).
        </p>

        <h2>1. Not a Law Firm — No Legal Advice</h2>
        <p>
          <strong>PolicyForge is not a law firm and does not engage in the practice of law or provide
          legal advice or legal representation.</strong> The documents, templates, and content generated
          by our Service are provided for general informational purposes only and do not constitute
          legal advice. Your use of the Service does not create an attorney-client relationship between
          you and PolicyForge.
        </p>
        <p>
          All documents generated through PolicyForge — whether template-based or AI-assisted — are
          starting drafts provided &quot;as is.&quot; They are not customized legal counsel for your specific
          situation. We strongly recommend that you consult with a qualified attorney licensed in your
          jurisdiction before using any generated document.
        </p>

        <h2>2. AI-Generated Content</h2>
        <p>
          Certain features of our Service use artificial intelligence to generate legal documents.
          AI-generated content may differ from what a qualified attorney would produce. AI output may
          be incomplete, may not address all legal requirements applicable to your situation, and should
          not be relied upon as a substitute for professional legal advice.
        </p>
        <p>
          You acknowledge that AI-generated content is produced by automated systems that may produce
          different results for similar inputs and that we do not guarantee the accuracy, completeness,
          or legal sufficiency of any AI-generated output.
        </p>

        <h2>3. Your Responsibilities</h2>
        <p>You are solely responsible for:</p>
        <ul>
          <li>Determining whether any document generated by the Service is appropriate for your use</li>
          <li>Reviewing all generated documents for accuracy and completeness before publication</li>
          <li>Ensuring your legal documents comply with all applicable laws and regulations</li>
          <li>Obtaining legal advice from a qualified attorney for your specific circumstances</li>
          <li>Maintaining the accuracy of information you provide to our Service</li>
        </ul>

        <h2>4. Account Terms</h2>
        <p>
          You must provide accurate information when creating an account. You are responsible for
          safeguarding your account credentials and for all activity under your account. You must
          notify us immediately of any unauthorized use.
        </p>

        <h2>5. Subscription and Payment</h2>
        <p>
          Paid plans are billed in advance on a recurring monthly basis. You may cancel your
          subscription at any time, and cancellation takes effect at the end of the current billing
          period. We do not provide refunds for partial billing periods, except within our 30-day
          money-back guarantee for new subscriptions.
        </p>

        <h2>6. Disclaimer of Warranties</h2>
        <p>
          <strong>THE SERVICE AND ALL GENERATED DOCUMENTS ARE PROVIDED &quot;AS IS&quot; AND &quot;AS AVAILABLE&quot;
          WITHOUT WARRANTIES OF ANY KIND, WHETHER EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO
          IMPLIED WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, AND
          NON-INFRINGEMENT.</strong>
        </p>
        <p>
          We do not warrant that generated documents will meet your specific requirements, comply
          with any particular law or regulation, protect your specific interests, or withstand
          challenges to their legal or factual sufficiency. The documents are not provided with any
          guarantee, warranty, or representation as to quality or suitability for any particular
          purpose.
        </p>

        <h2>7. Limitation of Liability</h2>
        <p>
          <strong>IN NO EVENT SHALL POLICYFORGE, ITS DIRECTORS, EMPLOYEES, PARTNERS, AGENTS,
          SUPPLIERS, OR AFFILIATES BE LIABLE FOR ANY INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL,
          OR PUNITIVE DAMAGES, INCLUDING WITHOUT LIMITATION, LOSS OF PROFITS, DATA, USE, GOODWILL,
          OR OTHER INTANGIBLE LOSSES, RESULTING FROM YOUR USE OF THE SERVICE OR ANY GENERATED
          DOCUMENTS.</strong>
        </p>
        <p>
          <strong>OUR TOTAL LIABILITY TO YOU FOR ALL CLAIMS ARISING FROM OR RELATING TO THE SERVICE
          SHALL NOT EXCEED THE AMOUNT PAID BY YOU TO POLICYFORGE IN THE TWELVE (12) MONTHS PRECEDING
          THE CLAIM.</strong>
        </p>

        <h2>8. Indemnification</h2>
        <p>
          You agree to indemnify, defend, and hold harmless PolicyForge and its officers, directors,
          employees, and agents from and against any claims, liabilities, damages, losses, costs, or
          expenses (including reasonable attorneys&apos; fees) arising from: (a) your use of generated
          documents; (b) your violation of these Terms; (c) your violation of any law or regulation;
          or (d) any third-party claims related to documents you generated or published using the
          Service.
        </p>

        <h2>9. Intellectual Property</h2>
        <p>
          Documents you generate through the Service are yours to use. However, the Service itself,
          including its templates, algorithms, design, and code, remain the property of PolicyForge.
          You may not reproduce, distribute, or create derivative works of the Service.
        </p>

        <h2>10. Termination</h2>
        <p>
          We may terminate or suspend your account at any time for violation of these Terms.
          Upon termination, your right to use the Service ceases immediately.
        </p>

        <h2>11. Changes to Terms</h2>
        <p>
          We may update these Terms at any time. We will notify you of material changes by posting
          the updated Terms on this page. Continued use of the Service after changes constitutes
          acceptance of the updated Terms.
        </p>

        <h2>12. Contact</h2>
        <p>
          Questions about these Terms? Contact us at{" "}
          <a href="mailto:support@policyforge.co">support@policyforge.co</a>.
        </p>
      </div>
    </section>
  );
}
