import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Disclaimer — PolicyForge",
};

export default function DisclaimerPage() {
  return (
    <section className="py-16">
      <div className="max-w-3xl mx-auto px-4 sm:px-6 prose prose-sm">
        <h1>Disclaimer</h1>
        <p><strong>Last updated:</strong> March 25, 2026</p>

        <h2>Not Legal Advice</h2>
        <p>
          PolicyForge is not a law firm and does not provide legal advice, legal representation,
          or legal counsel. The information and documents generated through our Service are provided
          for general informational and educational purposes only.
        </p>
        <p>
          All generated documents — whether created using templates or artificial intelligence — are
          automated outputs and do not constitute the practice of law. They should not be relied upon
          as a substitute for consultation with a qualified attorney licensed in your jurisdiction.
        </p>

        <h2>No Guarantees</h2>
        <p>
          We do not guarantee that any document generated by PolicyForge will comply with applicable
          laws, meet your specific legal requirements, or be sufficient for your particular situation.
          Laws and regulations vary by jurisdiction and change frequently. It is your responsibility to
          ensure that any document you use complies with all applicable laws.
        </p>

        <h2>AI-Generated Content</h2>
        <p>
          Our AI-powered document generation uses automated systems that may produce varying results.
          AI-generated content may be incomplete, may not accurately reflect current legal requirements,
          and may differ from what a licensed attorney would produce. AI-generated documents are
          provided on an &quot;as-is&quot; basis and used at your own risk.
        </p>

        <h2>Use at Your Own Risk</h2>
        <p>
          Your use of PolicyForge and any generated documents is at your sole risk. We recommend
          having all generated documents reviewed by a qualified attorney before publication or use.
        </p>

        <h2>Contact</h2>
        <p>
          If you have questions about this Disclaimer, contact us at{" "}
          <a href="mailto:support@policyforge.co">support@policyforge.co</a>.
        </p>
      </div>
    </section>
  );
}
