import { NextRequest } from "next/server";
import { createClient } from "@supabase/supabase-js";

const supabaseUrl = process.env.NEXT_PUBLIC_SUPABASE_URL || "";
const supabaseServiceKey = process.env.SUPABASE_SERVICE_ROLE_KEY || process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY || "";

export async function GET(
  _request: NextRequest,
  { params }: { params: Promise<{ policyId: string }> }
) {
  const { policyId } = await params;

  if (!supabaseUrl || !supabaseServiceKey) {
    return new Response("Configuration error", { status: 500 });
  }

  const supabase = createClient(supabaseUrl, supabaseServiceKey);

  const { data: policy, error } = await supabase
    .from("generated_policies")
    .select("generated_html, title, business_name, policy_type")
    .eq("id", policyId)
    .single();

  if (error || !policy) {
    return new Response("Policy not found", { status: 404 });
  }

  const policyTitle = policy.title || "Policy";
  const businessName = policy.business_name || "";

  const html = `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>${escapeHtml(policyTitle)} - ${escapeHtml(businessName)}</title>
  <meta name="description" content="${escapeHtml(policyTitle)} for ${escapeHtml(businessName)}. Generated by PolicyForge.">
  <meta name="robots" content="index, follow">
  <meta property="og:title" content="${escapeHtml(policyTitle)} - ${escapeHtml(businessName)}">
  <meta property="og:description" content="${escapeHtml(policyTitle)} for ${escapeHtml(businessName)}">
  <meta property="og:type" content="article">
  <style>
    *, *::before, *::after { box-sizing: border-box; margin: 0; padding: 0; }
    body {
      font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, 'Helvetica Neue', Arial, sans-serif;
      max-width: 800px;
      margin: 0 auto;
      padding: 48px 24px 64px;
      line-height: 1.7;
      color: #1a1a2e;
      background: #fafafa;
    }
    h1 {
      font-size: 28px;
      font-weight: 700;
      border-bottom: 2px solid #e5e7eb;
      padding-bottom: 14px;
      margin-bottom: 24px;
      color: #111827;
    }
    h2 {
      font-size: 20px;
      font-weight: 600;
      margin-top: 36px;
      margin-bottom: 12px;
      color: #1e40af;
    }
    h3 {
      font-size: 16px;
      font-weight: 600;
      margin-top: 24px;
      margin-bottom: 8px;
      color: #374151;
    }
    p { margin: 12px 0; }
    ul, ol { padding-left: 28px; margin: 12px 0; }
    li { margin-bottom: 8px; }
    a { color: #2563eb; text-decoration: underline; }
    a:hover { color: #1d4ed8; }
    .policy-footer {
      margin-top: 48px;
      padding-top: 24px;
      border-top: 1px solid #e5e7eb;
      text-align: center;
      font-size: 13px;
      color: #9ca3af;
    }
    .policy-footer a { color: #6b7280; text-decoration: none; }
    .policy-footer a:hover { text-decoration: underline; }

    @media print {
      body { padding: 20px; background: white; }
      .policy-footer { display: none; }
      a { color: inherit; text-decoration: none; }
      a::after { content: " (" attr(href) ")"; font-size: 0.85em; color: #666; }
    }
    @media (max-width: 640px) {
      body { padding: 24px 16px 48px; }
      h1 { font-size: 22px; }
      h2 { font-size: 17px; }
    }
  </style>
</head>
<body>
  <article>
    ${policy.generated_html}
  </article>
  <div class="policy-footer">
    Powered by <a href="https://policyforge.site" target="_blank" rel="noopener">PolicyForge</a>
  </div>
</body>
</html>`;

  return new Response(html, {
    status: 200,
    headers: {
      "Content-Type": "text/html; charset=utf-8",
      "Cache-Control": "public, max-age=3600, s-maxage=3600, stale-while-revalidate=86400",
    },
  });
}

function escapeHtml(str: string): string {
  return str
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;")
    .replace(/'/g, "&#039;");
}
